parameters:
#    likipe_frontend.example.class: Likipe\FrontendBundle\Example

services:
#    likipe_frontend.example:
#        class: %likipe_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
