parameters:
#    likipe_product.example.class: Likipe\ProductBundle\Example

services:
#    likipe_product.example:
#        class: %likipe_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
