parameters:
    likipe_uploadfile_services:      Likipe\ProductBundle\Services\UploadHandlerService

services:
    likipe.uploadfile.service:
        class: %likipe_uploadfile_services%
        arguments: ["@service_container"]
