assetic:
  assets:
    backend_js:
      inputs:
        - '%kernel.root_dir%/../web/backend/js/script.js'
        - '%kernel.root_dir%/../web/backend/js/vendor/bootstrap.min.js'
        - '%kernel.root_dir%/../web/backend/js/libs/jquery.uniform.min.js'
    backend_css:
      inputs:
        - '%kernel.root_dir%/../web/backend/css/bootstrap.min.css'
        - '%kernel.root_dir%/../web/backend/css/bootstrap-responsive.min.css'
        - '%kernel.root_dir%/../web/backend/css/uniform.default.min.css'
        - '%kernel.root_dir%/../web/backend/css/style.css'