imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    #- { resource: assets.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    write_to:       %kernel.root_dir%/../web/
    #bundles:        [LikipeBackendBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
              

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   %database_driver%
#        host:     %database_host%
#        port:     %database_port%
#        dbname:   %database_name%
#        user:     %database_user%
#        password: %database_password%
#        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    encryption: %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%

#Configure the FOSUserBundle
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: Likipe\FrontendBundle\Document\Member
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: KIMDANH8XX@gmail.com
        sender_name:    Admin Symfony2.3.1
    registration:
        confirmation:
            enabled: true # change to true for required email confirmation
            template: LikipeFrontendBundle:Registration:email.html.twig
        form:
            type: likipe_member_registration
    
# Doctrine MongoDB Configuration
doctrine_mongodb:
    connections: %mongodb_connections%
    default_database: %mongodb_database%
    document_managers:
        default:
            auto_mapping: true
    hydrator_namespace:   Hydrators
    hydrator_dir:         %kernel.cache_dir%/doctrine/odm/mongodb/Hydrators
    auto_generate_hydrator_classes:  true

trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    transformers: ['strip_js', 'strip_css', 'strip_comments']
    toolbar: ['document', 'clipboard', 'editing', 'elements', '/', 'basicstyles', 'paragraph', 'links', '/', 'insert', 'styles', 'tools']
    toolbar_groups:
        document: ['Source', '-','NewPage','Preview','Print','-','Templates']
        clipboard: ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo']
        editing: ['Find','Replace','-','SelectAll','-','SpellChecker']
        elements: ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'SelectionField', 'Button', 'ImageButton', 'HiddenField']
        basicstyles: ['Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat']
        paragraph: ['NumberedList','BulletedList','-','Outdent','Indent','-', 'Quote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter','JustifyRight','JustifyBlock']
        links: ['Link','Unlink','Anchor']
        insert: ['Image','Flash','Table','HorizontalRule', 'Smiley', 'Character', 'PageBreak', 'Iframe']
        styles: ['Styles','Format', 'Font', 'FontSize', 'TextColor', 'BGColor']
        tools: ['Maximize', 'ShowBlocks', 'About']
    ui_color: '#cccccc'
    startup_outline_blocks: true
    width: 800 #Integer or %
    height: 300 #Integer or %
    language: 'en-au'
    filebrowser_browse_url:
        url: %path%