imports:
    - { resource: config_prod.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_benchmark.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }