Likipe_Backend:
    resource: "@LikipeBackendBundle/Resources/config/routing.yml"
    prefix:   /backend
    
Likipe_Frontend:
    resource: "@LikipeFrontendBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"