security:
    encoders:
        Likipe\BackendBundle\Document\User : sha512
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_EDITOR
        ROLE_EDITOR:			ROLE_MEMBER

    providers:
        user:
            mongodb:
              class: LikipeBackendBundle:User
              property:	username
        fos_userbundle:
            mongodb:
              class: LikipeFrontendBundle:Member
              property:	email

    firewalls:
        backend:
            pattern: ^/backend/.*
            access_denied_url: /backend/denied
            provider: user
            form_login:
                check_path: /backend/login_check
                login_path: /backend/login
                default_target_path:	/backend/dashboard
            logout:
                path:   /backend/logout
                target: /
                invalidate_session: false
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~
                remember_me_parameter: _remember_me
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /login_check
                login_path: /login
                default_target_path:	/index
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            anonymous:    true
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/backend/user/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/post/add, roles: ROLE_EDITOR }
        - { path: ^/backend/post/edit/*, roles: ROLE_EDITOR }
        - { path: ^/backend/post, roles: ROLE_EDITOR }
        - { path: ^/backend/dashboard, roles: ROLE_EDITOR }
        - { path: ^/index/*, roles: ROLE_MEMBER }
        - { path: ^/backend/*, roles: ROLE_ADMIN, requires_channel: https }
