<?php

namespace Likipe\FrontendBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends DocumentRepository {
	
}