LikipeBackendBundle_Post_add:
    pattern:  /add.{_format}
    defaults: { _controller: "LikipeBackendBundle:Post:add", _format: html }
    requirements: 
      _format:  html

LikipeBackendBundle_Post_index:
    pattern:  /{iPage}
    defaults: { _controller: "LikipeBackendBundle:Post:index", iPage: 1 }
    requirements:
      iPage: \d+
    
LikipeBackendBundle_Post_edit:
    pattern:  /edit/{iPostId}
    defaults: { _controller: "LikipeBackendBundle:Post:edit" }
    
LikipeBackendBundle_Post_delete:
    pattern:  /delete/{iPostId}
    defaults: { _controller: "LikipeBackendBundle:Post:delete" }
    
LikipeBackendBundle_Comment_index:
    resource:   "@LikipeBackendBundle/Resources/config/routes/comment.yml"
    prefix:  /{iPostId}/comment